import { FREQUENCY_ROWS } from './lesson12Data'
import { formatProbability, frequenciesToProbabilities } from './languageModelMath'

export default function FrequencyProbabilityTable({ answers, totalAnswers, submitted, onChoose, onTotalChange, onSubmit, onRetry }: { answers: Record<string, string>; totalAnswers: Record<string, string>; submitted: readonly string[]; onChoose: (context: string, word: string) => void; onTotalChange: (context: string, value: string) => void; onSubmit: (context: string) => void; onRetry: (context: string) => void }) {
  return <div className="grid gap-5">{FREQUENCY_ROWS.map((row) => {
    const probabilities = frequenciesToProbabilities(row.candidates)
    const selected = answers[row.context]
    const isSubmitted = submitted.includes(row.context)
    const correct = isSubmitted && selected === row.answer
    const total = row.candidates.reduce((sum, item) => sum + item.count, 0)
    const totalCorrect = Number(totalAnswers[row.context]?.trim()) === total
    const probabilitySum = probabilities.reduce((sum, candidate) => sum + candidate.probability, 0)
    return <section key={row.context} className="rounded-2xl border border-slate-200 bg-slate-50 p-5" aria-labelledby={`frequency-${row.context}`}><div className="flex flex-wrap items-center justify-between gap-2"><h3 id={`frequency-${row.context}`} className="font-black">앞 단어: {row.context}</h3><span className="text-sm font-bold">행 전체 빈도: {total}</span></div><label className="mt-4 block text-sm font-bold">후보 빈도의 합을 직접 입력<input value={totalAnswers[row.context] ?? ''} inputMode="numeric" onChange={(event) => onTotalChange(row.context, event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 font-mono sm:max-w-48" /></label>{totalAnswers[row.context] ? <p className={`mt-2 text-sm font-bold ${totalCorrect ? 'text-emerald-700' : 'text-rose-700'}`}>{totalCorrect ? `✓ 후보 빈도 합은 ${total}입니다.` : '✕ 세 후보의 빈도를 모두 더해 보세요.'}</p> : null}<div className="mt-4 grid gap-3 sm:grid-cols-3">{probabilities.map((candidate) => <button key={candidate.word} type="button" disabled={isSubmitted} aria-pressed={selected === candidate.word} onClick={() => onChoose(row.context, candidate.word)} className={`rounded-xl border p-3 text-left disabled:cursor-not-allowed ${selected === candidate.word ? 'border-cyan-700 bg-cyan-50' : 'border-slate-300 bg-white'}`}><span className="flex justify-between gap-2 text-sm font-black"><span>{candidate.word}</span><span>{formatProbability(candidate.probability)}</span></span><span className="mt-1 block text-xs">빈도 {candidate.count} ÷ {total}</span><span className="mt-2 block h-3 overflow-hidden rounded-full bg-slate-200"><span className="block h-full rounded-full bg-cyan-600" style={{ width: `${candidate.probability * 100}%` }} /></span></button>)}</div><p className="mt-3 text-sm font-bold">내부 확률 합: {probabilitySum.toFixed(12)} · 화면 표시 합: 100.0%</p>{!isSubmitted ? <button type="button" disabled={!selected || !totalCorrect} onClick={() => onSubmit(row.context)} className="mt-4 min-h-11 rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white disabled:bg-slate-300">“{row.context}” 행 답 제출</button> : <><p className={`mt-3 text-sm font-bold ${correct ? 'text-emerald-700' : 'text-rose-700'}`} role="status">{correct ? `✓ ${row.context} 다음에는 “${row.answer}”가 가장 자주 나왔습니다.` : '✕ 빈도와 계산된 확률이 가장 큰 후보를 다시 선택하세요.'}</p>{!correct ? <button type="button" onClick={() => onRetry(row.context)} className="mt-3 min-h-11 rounded-xl border border-slate-300 bg-white px-4 text-sm font-bold">오답 다시 풀기</button> : null}</>}</section>
  })}</div>
}
