import { ArrowDown, ArrowRight } from 'lucide-react'

export default function RnnTransformerComparison({ rnnConfirmed, transformerConfirmed, onConfirmRnn, onConfirmTransformer }: { rnnConfirmed: boolean; transformerConfirmed: boolean; onConfirmRnn: () => void; onConfirmTransformer: () => void }) {
  const tokens = ['단어 1', '단어 2', '단어 3', '단어 4']
  return <div className="grid gap-5 lg:grid-cols-2">
    <section className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><h3 className="font-black text-violet-950">RNN 개념 흐름</h3><div className="mt-4 flex flex-col items-center gap-2 sm:flex-row">{tokens.map((token, index) => <div key={token} className="contents"><span className="w-full rounded-xl bg-white p-3 text-center text-sm font-bold">{token}</span>{index < tokens.length - 1 ? <><ArrowDown className="sm:hidden" aria-hidden="true" /><ArrowRight className="hidden shrink-0 sm:block" aria-hidden="true" /></> : null}</div>)}</div><p className="mt-4 text-sm leading-6">이전 단계의 상태 정보를 다음 단계로 전달하며 순차적으로 처리합니다.</p><button type="button" aria-pressed={rnnConfirmed} onClick={onConfirmRnn} className={`mt-4 min-h-11 rounded-xl border px-4 text-sm font-bold ${rnnConfirmed ? 'border-emerald-600 bg-emerald-50' : 'border-violet-500 bg-white'}`}>{rnnConfirmed ? '✓ RNN 흐름 확인' : 'RNN 흐름 확인'}</button></section>
    <section className="rounded-2xl border border-cyan-200 bg-cyan-50 p-5"><h3 className="font-black text-cyan-950">Transformer 개념 흐름</h3><div className="mt-4 grid grid-cols-4 gap-2">{tokens.map((token) => <span key={token} className="rounded-xl bg-white p-3 text-center text-xs font-bold sm:text-sm">{token}</span>)}</div><p className="mt-3 text-center text-2xl text-orange-600" aria-hidden="true">↘ ↕ ↙</p><p className="rounded-xl bg-white p-3 text-center text-sm font-black">Attention으로 단어 사이 관계 확인</p><p className="mt-4 text-sm leading-6">입력에 있는 여러 단어 관계를 병렬적으로 계산하기에 적합합니다.</p><button type="button" aria-pressed={transformerConfirmed} onClick={onConfirmTransformer} className={`mt-4 min-h-11 rounded-xl border px-4 text-sm font-bold ${transformerConfirmed ? 'border-emerald-600 bg-emerald-50' : 'border-cyan-500 bg-white'}`}>{transformerConfirmed ? '✓ Transformer 흐름 확인' : 'Transformer 흐름 확인'}</button></section>
  </div>
}

